using UnityEngine;


public class Enemy_Combat : MonoBehaviour
{
    public int damage = 1;
    public Transform attackPoint;
    public float weapongRange;
    public LayerMask playerLayer;
    public float KnockbackForce;
    public float stunTime;
    

   /*private void OnCollisionEnter2D(Collision2D collision)
     {
         collision.gameObject.GetComponent<PlayerHealth>().ChangeHealth(-damage);
     }*/
     

    public void Attack()
    {
        Collider2D[] hits = Physics2D.OverlapCircleAll(attackPoint.position, weapongRange, playerLayer);

        if (hits.Length > 0)
        {
            hits[0].GetComponent<PlayerHealth>().ChangeHealth(-damage);
            hits[0].GetComponent<PlayerMovement>().Knockback(transform, KnockbackForce, stunTime);
            Debug.Log("certo");
        }
    }   

}
